// Fuente de datos de proyectos (facilita escalabilidad / render dinámico futuro)
export const projects = [
  {
    id: 'eiffel-sp',
    title: 'Eiffel San Pedro',
    description: 'E-commerce de panadería sin gluten en San Pedro, Buenos Aires.',
    site: 'https://www.eiffel-sp.com.ar/',
    repo: 'https://github.com/example/eiffel-sp',
    img: 'eiffel-web.png',
    highlight: true,
    tags: ['Ecommerce', 'UI'],
  },
  {
    id: 'torito-villa-crespo',
    title: 'Torito Villa Crespo',
    description: 'Concepto de sitio web para parrilla argentina en Buenos Aires.',
    site: 'https://torito-villa-crespo.vercel.app/',
    repo: 'https://github.com/example/torito-villa-crespo',
    img: 'torito-web.png',
    tags: ['Landing', 'UI', 'Experimentos'],
  },
  {
    id: 'costee-del-rio',
    title: 'Costee del Río',
    description: 'Concepto de sitio web para restaurante costero en San Pedro, Buenos Aires.',
    site: 'https://costee-del-rio.vercel.app/',
    repo: 'https://github.com/example/costee-del-rio',
    img: 'costee-web.png',
    highlight: false,
    tags: ['Landing', 'UI', 'Experimentos'],
  },
  {
    id: 'kp-bags',
    title: 'KP Bags',
    description: 'E-commerce de carteras personalizadas y accesorios de moda.',
    site: 'https://kpbags.vercel.app/',
    repo: 'https://github.com/example/kp-bags',
    img: 'kpbags.png',
    tags: ['UI', 'Accesibilidad'],
  },
];
